version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: commit
        message:
          regex: ^[A-Za-z0-9._%+-]+@rippling.com$
      - do: commit
        message:
          regex: ^[A-Za-z0-9._%+-]+@rippling.com$
